### ISSUE TITLE
bishop and knight positions are fliped for the black pieces

### ISSUE THREAD

**Issue by Houda-DE** [stormsidali2001/react-chess-game-from-scratch#1]

**Comment by aghiles-medane** [comment]
Hi , out of curiosity i've being browsing your source code lately and i've noticed the issue then i've fixed it.
There was a mistake in the initial position of both the bishop and knight black pieces .

**Comment by stormsidali2001** [comment]
[aghiles-medane](https://github.com/aghiles-medane) . Your pull request is merged succesfully

thanks you all for your contributions !

@Houda-DE 
@aghiles-medane 
Best regards.
